import React from "react";
import { useState, useMemo } from "react";
import ExternalLinkIcon from "../images/externalLink.svg";
import BasicTable from "../react-table/BasicTable";
import ClientProfileImg from "../images/clientProfile.svg"
import ClientChartImg from "../images/clientChart.svg"

function MyPanel() {

  const [data, setData] = useState([
    {
      id: 10,
      first_name: "Myra",
      middle_name: "B",
      last_name: "Williams",
      nickname_preferred_name: "Myra",
      preferred_pronouns: "She/Her",
      email_address: "Myra@roots.org",
      mobile_number: 755068929,
      home_phone: "512-210-1007",
      work_phone: "512-100-2007",
      best_way_to_contact: "Mobile",
      primary_phone: "Mobile",
      comfortable_language: "English",
      other_language: "Spanish",
      date_of_birth: "1989-06-01",
      age: 35,
      sex: "Female",
      social_security_number: null,
      us_armed_forces: "Veteran",
      describe_the_place_you_live: "Coach Surfing",
      race: "Black",
      other_race: null,
      ethnicity: "Hispanic",
      gender_identity: "Female",
      other_gender_identity: null,
      sexual_orientation: "Heterosexual",
      other_sexual_orientation: null,
      mailing_address_line_1_address_n_usual_location: "1241 5th Avenue",
      mailing_address_line_2_address_n_usual_location: "Apt 11",
      city_address_n_usual_location: "Oakland",
      state_address_n_usual_location: "CA",
      zip_address_n_usual_location: "94621",
      where_can_we_usually_find_you_if_different_from_mailing_address: null,
      preferred_pharmacy_name: "CVS",
      preferred_pharmacy_location: "Leesburg",
      preferred_pharmacy_phone: "229-814-1010",
      insurance_primary_carrier_name: "Oakland Health Insurance",
      insurance_primary_subscriber_id: "123463",
      insurance_primary_subscriber_name: "Myra Williams",
      insurance_primary_group_name: "ABC130",
      insurance_primary_group_id: "97451",
      insurance_primary_relation_to_insured: "Self",
      insurance_primary_effective_from: "2023-01-01",
      insurance_primary_effective_to: "2023-12-31",
      insurance_secondary_carrier_name: "Oakland Health Insurance",
      insurance_secondary_subscriber_id: "123463",
      insurance_secondary_subscriber_name: "Myra Williams",
      insurance_secondary_group_name: "ABC130",
      insurance_secondary_group_id: "97451",
      insurance_secondary_relation_to_insured: "Self",
      insurance_secondary_effective_from: "2023-01-01",
      insurance_secondary_effective_to: "2023-12-21",
      insurance_tertiary_carrier_name: "Oakland Health Insurance",
      insurance_tertiary_subscriber_id: "123463",
      insurance_tertiary_subscriber_name: "Myra Williams",
      insurance_tertiary_group_name: "ABC130",
      insurance_tertiary_group_id: "97451",
      insurance_tertiary_relation_to_insured: "Self",
      insurance_tertiary_effective_from: "2023-01-01",
      insurance_tertiary_effective_to: "2023-12-21",
      emergency_contact_1_name: "Emer1",
      emergency_contact_1_email_address: "Emer@abc.com",
      emergency_contact_1_relationship: "Friend",
      emergency_contact_1_address_line_1: "19 7th Ave",
      emergency_contact_1_address_line_2: "Apt 11",
      emergency_contact_1_city: "Oakland",
      emergency_contact_1_state: "CA",
      emergency_contact_1_zip: "94621",
      emergency_contact_1_phone: 99806684,
      emergency_contact_2_name: "Emer2",
      emergency_contact_2_email_address: "Emer2@abc.com",
      emergency_contact_2_relationship: "Friend",
      emergency_contact_2_address_line_1: "19 7th Ave",
      emergency_contact_2_address_line_2: "Apt 11",
      emergency_contact_2_city: "Oakland",
      emergency_contact_2_state: "CA",
      emergency_contact_2_zip: "94621",
      emergency_contact_2_phone: 99806684,
      system_information_original_data_source: "Practice Fusion",
      system_information_import_notes: "Imported",
      system_information_import_date: "2023-10-10",
      system_information_prn: "12352",
      system_information_chart_number: "96726",
      system_information_system_id: "3092",
      status: "Engaged",
      hmis_id: 1234678,
      housing_status: "Unhold",
      ce_application_date: "9/20/2022",
      social_risk_score_housing: "high",
      latest_housing_status: 3818,
      staff_signed_to_client: "Engaged",
      last_reviewed: "8/14/2023",
      latest_encounter_date: "8/14/2023",
      latest_encounter_note: "Followed up regarding survey",
      date_assigned: "2022-01-16",
      program: "ECM",
    },
    {
      id: 11,
      first_name: "Lucas",
      middle_name: "C",
      last_name: "Turner",
      nickname_preferred_name: "Lucas",
      preferred_pronouns: "He/His",
      email_address: "Lucas@roots.org",
      mobile_number: 220912475,
      home_phone: "512-210-1008",
      work_phone: "512-100-2008",
      best_way_to_contact: "Mobile",
      primary_phone: "Mobile",
      comfortable_language: "English",
      other_language: "Spanish",
      date_of_birth: "1934-03-14",
      age: 90,
      sex: "Male",
      social_security_number: null,
      us_armed_forces: "Veteran",
      describe_the_place_you_live: "House or Apartment",
      race: "Black",
      other_race: null,
      ethnicity: "Hispanic",
      gender_identity: "Male",
      other_gender_identity: null,
      sexual_orientation: "Heterosexual",
      other_sexual_orientation: null,
      mailing_address_line_1_address_n_usual_location: "1242 5th Avenue",
      mailing_address_line_2_address_n_usual_location: "Apt 12",
      city_address_n_usual_location: "Oakland",
      state_address_n_usual_location: "CA",
      zip_address_n_usual_location: "94621",
      where_can_we_usually_find_you_if_different_from_mailing_address: null,
      preferred_pharmacy_name: "Oakland Pharmacy",
      preferred_pharmacy_location: "Leesburg",
      preferred_pharmacy_phone: "229-814-1011",
      insurance_primary_carrier_name: "Alameda Alliance",
      insurance_primary_subscriber_id: "123464",
      insurance_primary_subscriber_name: "Lucas Turner",
      insurance_primary_group_name: "ABC131",
      insurance_primary_group_id: "97451",
      insurance_primary_relation_to_insured: "Self",
      insurance_primary_effective_from: "2023-01-01",
      insurance_primary_effective_to: "2023-12-31",
      insurance_secondary_carrier_name: "Alameda Alliance",
      insurance_secondary_subscriber_id: "123464",
      insurance_secondary_subscriber_name: "Lucas Turner",
      insurance_secondary_group_name: "ABC131",
      insurance_secondary_group_id: "97451",
      insurance_secondary_relation_to_insured: "Self",
      insurance_secondary_effective_from: "2023-01-01",
      insurance_secondary_effective_to: "2023-12-21",
      insurance_tertiary_carrier_name: "Alameda Alliance",
      insurance_tertiary_subscriber_id: "123464",
      insurance_tertiary_subscriber_name: "Lucas Turner",
      insurance_tertiary_group_name: "ABC131",
      insurance_tertiary_group_id: "97451",
      insurance_tertiary_relation_to_insured: "Self",
      insurance_tertiary_effective_from: "2023-01-01",
      insurance_tertiary_effective_to: "2023-12-21",
      emergency_contact_1_name: "Emer1",
      emergency_contact_1_email_address: "Emer@abc.com",
      emergency_contact_1_relationship: "Friend",
      emergency_contact_1_address_line_1: "20 7th Ave",
      emergency_contact_1_address_line_2: "Apt 12",
      emergency_contact_1_city: "Oakland",
      emergency_contact_1_state: "CA",
      emergency_contact_1_zip: "94621",
      emergency_contact_1_phone: 99806685,
      emergency_contact_2_name: "Emer2",
      emergency_contact_2_email_address: "Emer2@abc.com",
      emergency_contact_2_relationship: "Friend",
      emergency_contact_2_address_line_1: "20 7th Ave",
      emergency_contact_2_address_line_2: "Apt 12",
      emergency_contact_2_city: "Oakland",
      emergency_contact_2_state: "CA",
      emergency_contact_2_zip: "94621",
      emergency_contact_2_phone: 99806685,
      system_information_original_data_source: "Practice Fusion",
      system_information_import_notes: "Imported",
      system_information_import_date: "2023-10-10",
      system_information_prn: "12353",
      system_information_chart_number: "96717",
      system_information_system_id: "3093",
      status: "Engaged",
      hmis_id: 1234678,
      housing_status: "Unhold",
      ce_application_date: "9/20/2022",
      social_risk_score_housing: "high",
      latest_housing_status: 3818,
      staff_signed_to_client: "Engaged",
      last_reviewed: "8/14/2023",
      latest_encounter_date: "8/14/2023",
      latest_encounter_note: "Followed up regarding survey",
      date_assigned: "2022-01-16",
      program: "ECM",
    },
    {
      id: 11,
      first_name: "Lucas",
      middle_name: "C",
      last_name: "Turner",
      nickname_preferred_name: "Lucas",
      preferred_pronouns: "He/His",
      email_address: "Lucas@roots.org",
      mobile_number: 220912475,
      home_phone: "512-210-1008",
      work_phone: "512-100-2008",
      best_way_to_contact: "Mobile",
      primary_phone: "Mobile",
      comfortable_language: "English",
      other_language: "Spanish",
      date_of_birth: "1934-03-14",
      age: 90,
      sex: "Male",
      social_security_number: null,
      us_armed_forces: "Veteran",
      describe_the_place_you_live: "House or Apartment",
      race: "Black",
      other_race: null,
      ethnicity: "Hispanic",
      gender_identity: "Male",
      other_gender_identity: null,
      sexual_orientation: "Heterosexual",
      other_sexual_orientation: null,
      mailing_address_line_1_address_n_usual_location: "1242 5th Avenue",
      mailing_address_line_2_address_n_usual_location: "Apt 12",
      city_address_n_usual_location: "Oakland",
      state_address_n_usual_location: "CA",
      zip_address_n_usual_location: "94621",
      where_can_we_usually_find_you_if_different_from_mailing_address: null,
      preferred_pharmacy_name: "Oakland Pharmacy",
      preferred_pharmacy_location: "Leesburg",
      preferred_pharmacy_phone: "229-814-1011",
      insurance_primary_carrier_name: "Alameda Alliance",
      insurance_primary_subscriber_id: "123464",
      insurance_primary_subscriber_name: "Lucas Turner",
      insurance_primary_group_name: "ABC131",
      insurance_primary_group_id: "97451",
      insurance_primary_relation_to_insured: "Self",
      insurance_primary_effective_from: "2023-01-01",
      insurance_primary_effective_to: "2023-12-31",
      insurance_secondary_carrier_name: "Alameda Alliance",
      insurance_secondary_subscriber_id: "123464",
      insurance_secondary_subscriber_name: "Lucas Turner",
      insurance_secondary_group_name: "ABC131",
      insurance_secondary_group_id: "97451",
      insurance_secondary_relation_to_insured: "Self",
      insurance_secondary_effective_from: "2023-01-01",
      insurance_secondary_effective_to: "2023-12-21",
      insurance_tertiary_carrier_name: "Alameda Alliance",
      insurance_tertiary_subscriber_id: "123464",
      insurance_tertiary_subscriber_name: "Lucas Turner",
      insurance_tertiary_group_name: "ABC131",
      insurance_tertiary_group_id: "97451",
      insurance_tertiary_relation_to_insured: "Self",
      insurance_tertiary_effective_from: "2023-01-01",
      insurance_tertiary_effective_to: "2023-12-21",
      emergency_contact_1_name: "Emer1",
      emergency_contact_1_email_address: "Emer@abc.com",
      emergency_contact_1_relationship: "Friend",
      emergency_contact_1_address_line_1: "20 7th Ave",
      emergency_contact_1_address_line_2: "Apt 12",
      emergency_contact_1_city: "Oakland",
      emergency_contact_1_state: "CA",
      emergency_contact_1_zip: "94621",
      emergency_contact_1_phone: 99806685,
      emergency_contact_2_name: "Emer2",
      emergency_contact_2_email_address: "Emer2@abc.com",
      emergency_contact_2_relationship: "Friend",
      emergency_contact_2_address_line_1: "20 7th Ave",
      emergency_contact_2_address_line_2: "Apt 12",
      emergency_contact_2_city: "Oakland",
      emergency_contact_2_state: "CA",
      emergency_contact_2_zip: "94621",
      emergency_contact_2_phone: 99806685,
      system_information_original_data_source: "Practice Fusion",
      system_information_import_notes: "Imported",
      system_information_import_date: "2023-10-10",
      system_information_prn: "12353",
      system_information_chart_number: "96717",
      system_information_system_id: "3093",
      status: "Engaged",
      hmis_id: 1234678,
      housing_status: "Unhold",
      ce_application_date: "9/20/2022",
      social_risk_score_housing: "high",
      latest_housing_status: 3818,
      staff_signed_to_client: "Engaged",
      last_reviewed: "8/14/2023",
      latest_encounter_date: "8/14/2023",
      latest_encounter_note: "Followed up regarding survey",
      date_assigned: "2022-01-16",
      program: "Diabetes",
    },
    {
      id: 11,
      first_name: "Lucas",
      middle_name: "C",
      last_name: "Turner",
      nickname_preferred_name: "Lucas",
      preferred_pronouns: "He/His",
      email_address: "Lucas@roots.org",
      mobile_number: 220912475,
      home_phone: "512-210-1008",
      work_phone: "512-100-2008",
      best_way_to_contact: "Mobile",
      primary_phone: "Mobile",
      comfortable_language: "English",
      other_language: "Spanish",
      date_of_birth: "1934-03-14",
      age: 90,
      sex: "Male",
      social_security_number: null,
      us_armed_forces: "Veteran",
      describe_the_place_you_live: "House or Apartment",
      race: "Black",
      other_race: null,
      ethnicity: "Hispanic",
      gender_identity: "Male",
      other_gender_identity: null,
      sexual_orientation: "Heterosexual",
      other_sexual_orientation: null,
      mailing_address_line_1_address_n_usual_location: "1242 5th Avenue",
      mailing_address_line_2_address_n_usual_location: "Apt 12",
      city_address_n_usual_location: "Oakland",
      state_address_n_usual_location: "CA",
      zip_address_n_usual_location: "94621",
      where_can_we_usually_find_you_if_different_from_mailing_address: null,
      preferred_pharmacy_name: "Oakland Pharmacy",
      preferred_pharmacy_location: "Leesburg",
      preferred_pharmacy_phone: "229-814-1011",
      insurance_primary_carrier_name: "Alameda Alliance",
      insurance_primary_subscriber_id: "123464",
      insurance_primary_subscriber_name: "Lucas Turner",
      insurance_primary_group_name: "ABC131",
      insurance_primary_group_id: "97451",
      insurance_primary_relation_to_insured: "Self",
      insurance_primary_effective_from: "2023-01-01",
      insurance_primary_effective_to: "2023-12-31",
      insurance_secondary_carrier_name: "Alameda Alliance",
      insurance_secondary_subscriber_id: "123464",
      insurance_secondary_subscriber_name: "Lucas Turner",
      insurance_secondary_group_name: "ABC131",
      insurance_secondary_group_id: "97451",
      insurance_secondary_relation_to_insured: "Self",
      insurance_secondary_effective_from: "2023-01-01",
      insurance_secondary_effective_to: "2023-12-21",
      insurance_tertiary_carrier_name: "Alameda Alliance",
      insurance_tertiary_subscriber_id: "123464",
      insurance_tertiary_subscriber_name: "Lucas Turner",
      insurance_tertiary_group_name: "ABC131",
      insurance_tertiary_group_id: "97451",
      insurance_tertiary_relation_to_insured: "Self",
      insurance_tertiary_effective_from: "2023-01-01",
      insurance_tertiary_effective_to: "2023-12-21",
      emergency_contact_1_name: "Emer1",
      emergency_contact_1_email_address: "Emer@abc.com",
      emergency_contact_1_relationship: "Friend",
      emergency_contact_1_address_line_1: "20 7th Ave",
      emergency_contact_1_address_line_2: "Apt 12",
      emergency_contact_1_city: "Oakland",
      emergency_contact_1_state: "CA",
      emergency_contact_1_zip: "94621",
      emergency_contact_1_phone: 99806685,
      emergency_contact_2_name: "Emer2",
      emergency_contact_2_email_address: "Emer2@abc.com",
      emergency_contact_2_relationship: "Friend",
      emergency_contact_2_address_line_1: "20 7th Ave",
      emergency_contact_2_address_line_2: "Apt 12",
      emergency_contact_2_city: "Oakland",
      emergency_contact_2_state: "CA",
      emergency_contact_2_zip: "94621",
      emergency_contact_2_phone: 99806685,
      system_information_original_data_source: "Practice Fusion",
      system_information_import_notes: "Imported",
      system_information_import_date: "2023-10-10",
      system_information_prn: "12353",
      system_information_chart_number: "96717",
      system_information_system_id: "3093",
      status: "Engaged",
      hmis_id: 1234678,
      housing_status: "Unhold",
      ce_application_date: "9/20/2022",
      social_risk_score_housing: "high",
      latest_housing_status: 3818,
      staff_signed_to_client: "Engaged",
      last_reviewed: "8/14/2023",
      latest_encounter_date: "8/14/2023",
      latest_encounter_note: "Followed up regarding survey",
      date_assigned: "2022-01-16",
      program: "Diabetes",
    },
    {
      id: 11,
      first_name: "Lucas",
      middle_name: "C",
      last_name: "Turner",
      nickname_preferred_name: "Lucas",
      preferred_pronouns: "He/His",
      email_address: "Lucas@roots.org",
      mobile_number: 220912475,
      home_phone: "512-210-1008",
      work_phone: "512-100-2008",
      best_way_to_contact: "Mobile",
      primary_phone: "Mobile",
      comfortable_language: "English",
      other_language: "Spanish",
      date_of_birth: "1934-03-14",
      age: 90,
      sex: "Male",
      social_security_number: null,
      us_armed_forces: "Veteran",
      describe_the_place_you_live: "House or Apartment",
      race: "Black",
      other_race: null,
      ethnicity: "Hispanic",
      gender_identity: "Male",
      other_gender_identity: null,
      sexual_orientation: "Heterosexual",
      other_sexual_orientation: null,
      mailing_address_line_1_address_n_usual_location: "1242 5th Avenue",
      mailing_address_line_2_address_n_usual_location: "Apt 12",
      city_address_n_usual_location: "Oakland",
      state_address_n_usual_location: "CA",
      zip_address_n_usual_location: "94621",
      where_can_we_usually_find_you_if_different_from_mailing_address: null,
      preferred_pharmacy_name: "Oakland Pharmacy",
      preferred_pharmacy_location: "Leesburg",
      preferred_pharmacy_phone: "229-814-1011",
      insurance_primary_carrier_name: "Alameda Alliance",
      insurance_primary_subscriber_id: "123464",
      insurance_primary_subscriber_name: "Lucas Turner",
      insurance_primary_group_name: "ABC131",
      insurance_primary_group_id: "97451",
      insurance_primary_relation_to_insured: "Self",
      insurance_primary_effective_from: "2023-01-01",
      insurance_primary_effective_to: "2023-12-31",
      insurance_secondary_carrier_name: "Alameda Alliance",
      insurance_secondary_subscriber_id: "123464",
      insurance_secondary_subscriber_name: "Lucas Turner",
      insurance_secondary_group_name: "ABC131",
      insurance_secondary_group_id: "97451",
      insurance_secondary_relation_to_insured: "Self",
      insurance_secondary_effective_from: "2023-01-01",
      insurance_secondary_effective_to: "2023-12-21",
      insurance_tertiary_carrier_name: "Alameda Alliance",
      insurance_tertiary_subscriber_id: "123464",
      insurance_tertiary_subscriber_name: "Lucas Turner",
      insurance_tertiary_group_name: "ABC131",
      insurance_tertiary_group_id: "97451",
      insurance_tertiary_relation_to_insured: "Self",
      insurance_tertiary_effective_from: "2023-01-01",
      insurance_tertiary_effective_to: "2023-12-21",
      emergency_contact_1_name: "Emer1",
      emergency_contact_1_email_address: "Emer@abc.com",
      emergency_contact_1_relationship: "Friend",
      emergency_contact_1_address_line_1: "20 7th Ave",
      emergency_contact_1_address_line_2: "Apt 12",
      emergency_contact_1_city: "Oakland",
      emergency_contact_1_state: "CA",
      emergency_contact_1_zip: "94621",
      emergency_contact_1_phone: 99806685,
      emergency_contact_2_name: "Emer2",
      emergency_contact_2_email_address: "Emer2@abc.com",
      emergency_contact_2_relationship: "Friend",
      emergency_contact_2_address_line_1: "20 7th Ave",
      emergency_contact_2_address_line_2: "Apt 12",
      emergency_contact_2_city: "Oakland",
      emergency_contact_2_state: "CA",
      emergency_contact_2_zip: "94621",
      emergency_contact_2_phone: 99806685,
      system_information_original_data_source: "Practice Fusion",
      system_information_import_notes: "Imported",
      system_information_import_date: "2023-10-10",
      system_information_prn: "12353",
      system_information_chart_number: "96717",
      system_information_system_id: "3093",
      status: "Engaged",
      hmis_id: 1234678,
      housing_status: "Unhold",
      ce_application_date: "9/20/2022",
      social_risk_score_housing: "high",
      latest_housing_status: 3818,
      staff_signed_to_client: "Engaged",
      last_reviewed: "8/14/2023",
      latest_encounter_date: "8/14/2023",
      latest_encounter_note: "Followed up regarding survey",
      date_assigned: "2022-01-16",
      program: "STOMP",
    },
  ]);

  const columns = useMemo(
    () => [
      {
        Header: "Client",
        accessor: "first_name",
        Cell: ({ row }) => (`${row.original.first_name}, ${row.original.last_name}`),
      },
      {
        Header: "D.O.B",
        accessor: "date_of_birth",
      },
      {
        Header: "Gender",
        accessor: "sex",
      },
      {
        Header: "Phone Number",
        accessor: "mobile_number",
      },
      {
        Header: "Date Assigned",
        accessor: "date_assigned",
      },
      {
        Header: "Program",
        accessor: "program",
      },
      {
        Header: "Client Profile",
        Cell: () => (<img src={ClientProfileImg} className="size-8 mx-auto" alt="client" />),
      },
      {
        Header: "Client Chart",
        Cell: () => (<img src={ClientChartImg} className="size-6 mx-auto" alt="client" />),
      },
    ],
    []
  );

  return (
    <div className="w-full bg-white rounded-md shadow-md flex flex-col">
      <div className="flex justify-between items-center mx-8 mt-2">
        <div className="flex items-center space-x-4">
          <span className="text-lg font-medium">My Panel</span>
          <img src={ExternalLinkIcon} className="size-4" alt="link" />
        </div>
        <div>
          <button className="px-3 py-1 border-2 rounded-sm border-[#2F9384] text-[#2F9384]">
            View all
          </button>
        </div>
      </div>
      <hr className="w-[98%] mx-auto my-2" />
      <div className="w-[96%] mx-auto my-3 overflow-x-auto">
        <BasicTable type={'myPanel'} columns={columns} data={data} />
      </div>
    </div>
  );
}

export default MyPanel;
